### ISSUE TITLE
The lastest version will cause the error occured in build，please pay attention to it

### ISSUE THREAD

**Issue by lichuyuan224** [privateOmega/html-to-docx#112]
![image](https://user-images.githubusercontent.com/83797559/147525254-592561f4-5e4d-4687-bee1-e1594433076c.png)

**Comment by erenard** [comment]
I have encountered the same problem.
Webpack complain about not knowing how to load the esm module.
Others dependencies (vue and apollo) are loaded from esm module without problem.

**Comment by privateOmega** [comment]
@lichuyuan224 @erenard Seems like I have figured out the issue, and its for some reason with the optional chaining I introduced with latest changes. I will try to solve it soon and release a build.

**Comment by privateOmega** [comment]
Seems like this is not the only issue, even version updates to deps has sprung up some other issues, which I am trying to figure out. If either of you have some experience with bundling in JS, that would be a great help.

**Comment by JonasJonny** [comment]
I remembered this issue https://github.com/toji/gl-matrix/issues/439#issuecomment-934768169, just #FYI.

**Comment by pdziak** [comment]
Unfortunately, I'm experiencing the same error described in the first post. Will this be fixed?

**Comment by privateOmega** [comment]
@pdziak I have had tried several ways to fix it, but for some reason, it isnt getting fixed, probably due to my lack of knowledge of module bundlers.

**Comment by privateOmega** [comment]
Guys, I have finally figured out a fix, which was basically a revert on 2 package updates I did, I have no clue how to make it run with the new upgrades, but this [new version - v1.3.2](https://www.npmjs.com/package/html-to-docx/v/1.3.2) of html-to-docx should work with react just like how it did earlier for you. I apologize for the inconvenience caused. 

Also I am closing this issue, since its a non-issue, but feel free to re-open it, if someone is still facing this issue.
