### ISSUE TITLE
Html with <script> is not working.

### ISSUE THREAD

**Issue by venkadesh-p** [privateOmega/html-to-docx#25]
I am tying to generate word doc from html string. My html string contains script tag. html-to-docx is not rendering the html with the executed script. I am providing the sample for reference below,

```
let str2 = '<!DOCTYPE html><html><body><h1>The script element</h1><p id="demo"></p><script>document.getElementById("demo").innerHTML = "Hello JavaScript!";</script></body></html>'
const fileBuffer = await HTMLtoDOCX(str2, null, {});
fs.writeFile(filePath, fileBuffer, (error) => {
     if (error) {
         console.log('Docx file creation failed');
      }
      console.log('Docx file created successfully');
});
```
How to get it working?

**Comment by privateOmega** [comment]
@venkadesh-p Ah well sorry, this package doesnt rely on any full brown browser or any similiar platforms to execute the script first and then use the generated HTML for docx preparation, this is just an average HTML parser, which generates equivalent OOXML xml script. So script execution is definitely not possible ever and is out of the scope of the package.

Closing this issue because there's no point as of now to keep it open, feel free to reopen it if you have some ideas on how to implement the required feature. I will be happy to discuss ideas.

**Comment by privateOmega** [comment]
Also as a idea to bounce around when I think about this specific feature, is to have a browser layer before this package's method is called, you could basically make use of a library like [puppeteer](https://github.com/puppeteer/puppeteer) which would run a headless browser underneath it and get the final HTML as input to the html-to-docx package.

**Comment by venkadesh-p** [comment]
@privateOmega Thanks for the reply. I will try with puppeteer. Thanks again.
