### ISSUE TITLE
Using library in typescript/angular

### ISSUE THREAD

**Issue by meta-akshita-agrawal** [privateOmega/html-to-docx#47]

**Comment by meta-akshita-agrawal** [comment]
I tried
`import * as htmlToDocx from 'html-to-docx'`
`import {htmlToDocx} from 'html-to-docx'`
`const htmlToDocx = require('html-to-docx')`
also here is one of your [example](https://github.com/privateOmega/html-to-docx/blob/21354f9459004ac128d463c8a1e44944b5db2bdf/example/example.js#L5) I tried to import this too. But that didn't work too

**Comment by privateOmega** [comment]
@meta-akshita-agrawal What do you mean it didn't work? Any particular errors or it says htmlToDocx is undefined or something? Could you please post the exact log?

**Comment by meta-akshita-agrawal** [comment]
![image](https://user-images.githubusercontent.com/41181785/104900068-9d623d80-59a1-11eb-8ccf-22c065aedc59.png)

**Comment by meta-akshita-agrawal** [comment]
`ERROR in ./node_modules/clean-css/lib/reader/read-sources.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\clean-css\lib\reader'
ERROR in ./node_modules/clean-css/lib/reader/apply-source-maps.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\clean-css\lib\reader'
ERROR in ./node_modules/clean-css/lib/reader/load-original-sources.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\clean-css\lib\reader'
ERROR in ./node_modules/html-to-docx/node_modules/image-size/dist/index.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\html-to-docx\node_modules\image-size\dist'
ERROR in ./node_modules/html-to-docx/node_modules/image-size/dist/fs.promises.js
Module not found: Error: Can't resolve 'fs' in node_modules\html-to-docx\node_modules\image-size\dist'
ERROR in ./node_modules/html-to-docx/node_modules/image-size/dist/types/tiff.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\html-to-docx\node_modules\image-size\dist\types'
ERROR in ./node_modules/uglify-js/tools/node.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\uglify-js\tools'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'`

**Comment by privateOmega** [comment]
@meta-akshita-agrawal Yup that error log makes sense, because `fs` is a node.js module, hence stubbed out in browser environment and I forgot that I use a dependency which internally depends on fs module.

 This has been a long running issue that I haven't had much time to focus on, I had created a [branch](https://github.com/privateOmega/html-to-docx/tree/feature/browser-example) for that. I will try to work on it sometime soon.
 
In the meanwhile I guess you can install using that branch and it should work, but you might be missing out on some features for the time being, which I can hopefully rebase it to latest version by tonight.

Closing this issue to track it at [one place](https://github.com/privateOmega/html-to-docx/issues/3).

**Comment by privateOmega** [comment]
@meta-akshita-agrawal Yup that error log makes sense, because `fs` is a node.js module, hence stubbed out in browser environment and I forgot that I use a dependency which internally depends on fs module.

 This has been a long running issue that I haven't had much time to focus on, I had created a [branch](https://github.com/privateOmega/html-to-docx/tree/feature/browser-example) for that. I will try to work on it sometime soon.
 
In the meanwhile I guess you can install using that branch and it should work, but you might be missing out on some features for the time being, which I can hopefully rebase it to latest version by tonight.

Closing this issue to track it at [one place](https://github.com/privateOmega/html-to-docx/issues/3).

**Comment by meta-akshita-agrawal** [comment]
Thanks for the update

**Comment by joeskeen** [comment]
@privateOmega any update on when that branch can be rebased on the latest version? I'm guessing it didn't happen "tonight" (16 days ago) ;)

**Comment by privateOmega** [comment]
@joeskeen Please checkout the branch now, it was rebased against develop, hence should have the latest features, unfortunately I can't commit any time at present to this feature now due to my other commitments, but it should work for your use case I guess. Feel free to comment below, if you are facing some issues on that.

**Comment by ronanjia** [comment]
hi, @privateOmega, Help please, sorry i just can't get it to work in browser.
i installed the feature/browser-example branch, and only got '/example' and '/node_modules' 2 directories in my 'html-to-docx' package
![image](https://user-images.githubusercontent.com/5581839/110495615-a49b0180-812f-11eb-8c4c-0b36f5f0e0d0.png)

I thought some key files might be lost, so i copied '/src', '/template', 'index.js' into the package folder, just got the same error of  Can't resolve 'crypto', 'fs', 'path' when i run from "generateContainer" in index.js
![image](https://user-images.githubusercontent.com/5581839/110496015-0a878900-8130-11eb-87f2-282e94949fb6.png)

So is it possible to use this package in a react or an angular project for browser?

**Comment by tco7878** [comment]
@privateOmega Thank you for this long awaited feature :) 

I am currently trying to get it to work in an Angular Application using the following code:

```
        const htmlString = '<b>Test</b>'
        const fileBuffer = await HTMLtoDOCX(htmlString, null, {
            table: {row: {cantSplit: true}},
            footer: true,
            pageNumber: true,
        });
        saveAs(fileBuffer, "document.docx");
```

However I am getting the following error:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot call a class as a function
TypeError: Cannot call a class as a function
    at _classCallCheck (classCallCheck.js:3)
    at new NodeImpl (NodeImpl.js:18)
    at DocumentImpl._createSuperInternal (createSuper.js:15)
    at new DocumentImpl (DocumentImpl.js:21)
    at Object.create_document (CreateAlgorithm.js:55)
    at new WindowImpl (WindowImpl.js:19)
    at Function._create (WindowImpl.js:29)
    at Object.create_window (CreateAlgorithm.js:41)
    at DOMImpl.get (DOMImpl.js:53)
    at new DOMImplementationImpl (DOMImplementationImpl.js:18)
    at resolvePromise (zone.js:1255)
    at zone.js:1162
    at rejected (components-gvp-overview-gvp-module.js:66753)
    at ZoneDelegate.invoke (zone.js:400)
    at Object.onInvoke (core.js:28553)
    at ZoneDelegate.invoke (zone.js:399)
    at Zone.run (zone.js:160)
    at zone.js:1318
    at ZoneDelegate.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28540)
```

Any Ideas on how to resolve that?

**Comment by privateOmega** [comment]
@tco7878 Why are you importing and using the umd build? 

Can't you just do `import * as htmlToDocx from 'html-to-docx'` and I guess that should work.

**Comment by tco7878** [comment]
@privateOmega thanks for your answer. Unfortunately this does not help. I did try importing from 'html-to-docx' as well as importing the esm and umd build directly. The error remains the same

My Angular project is targeting ES5 maybe it is related to that.

**Comment by privateOmega** [comment]
@tco7878 Sorry I couldn't be of more help, I am not that used to typescript and also just curious, do you get the the same error when you use the `import * as htmlToDocx from 'html-to-docx'`?

**Comment by tco7878** [comment]
@privateOmega I've just tested it and `import htmlToDocx from 'html-to-docx'` leads to the same error. I've also tested `import {htmlToDocx} from 'html-to-docx' ` and `const htmlToDocx = require('html-to-docx')` as well as `const htmlToDocx = require('html-to-docx/dist/html-to-docx.esm')`  and `const htmlToDocx = require('html-to-docx/dist/html-to-docx.umd')`

**Comment by tco7878** [comment]
Update: I've found out that this issue only occurs when targeting ES5. When targeting ES2015 in Angular html-to-docx works like a charm. Unfortunately targeting es2015 is not an option for us. I'll try to further investigate this issue

**Comment by ammarmohamed2016** [comment]
Any update about this issue @tco7878 @privateOmega ?

**Comment by artemdumanov** [comment]
As a workaround, you can use 
`// @ts-ignore`
