### ISSUE TITLE
superscript <sup> renders as subscript

### ISSUE THREAD

**Issue by martin-lorenz** [privateOmega/html-to-docx#51]
When using the `<sup>` tag, the result renders as subscript.

**Comment by privateOmega** [comment]
@martin-lorenz Yea I just checked it out and seems you were right, I had wrongly written the argument for the method which builds the subscript and superscript elements. I have fixed it with the latest release. PTAL.

**Comment by martin-lorenz** [comment]
Hi @privateOmega thank you very much for taking a look. I just installed 1.1.34, but <sup> still renders a subscript format. Can you confirm that this fix has made it into 1.1.34? Thanks again!!!

**Comment by privateOmega** [comment]
@martin-lorenz I have double checked the issue and it seems like it was merged, released, and works with v1.1.34. I am attaching a screenshot of the feature being tried out. Maybe posting the usage and relevant part of html would help narrow down the issue.

![Screenshot 2021-02-19 at 11 59 35 PM](https://user-images.githubusercontent.com/10467133/108546219-d37f3e00-730e-11eb-824a-ebf0b9a7790d.png)

**Comment by simon-jouet** [comment]
Hi @privateOmega just noticed the same issue locally running 1.1.34 the super script are rendered as subscript. 

With a simple HTML like this

```
const htmlString = `
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf8" />
</head>

<body>
    <p>Hello <sup>world</sup></p>
</body>

</html>
`;
```
I get the following

![image](https://user-images.githubusercontent.com/832495/120658873-bd405c80-c47d-11eb-99df-ad3ffb945f8c.png)

I think the issue is that the npm package hasn't been rebuilt? Looking at node_modules/html-to-docx/dist/html-to-docx.esm.js I can see `case"sup":return buildVertAlign("subscript")` which shouldn't be the case from https://github.com/privateOmega/html-to-docx/commit/2fd87fd406a97732e24d7f191147638ee7053ced

**Comment by andreeapurta** [comment]
The problem still persists.
