### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by zees98** [privateOmega/html-to-docx#94]
Hello, 
I am trying to use html2docx for a react project. But for some reason it keeps crashing with the error: 
**TypeError: Cannot read properties of undefined (reading 'type')**

I have tried it with the example and then changed it. Both codes yield the same error. 

```
var html = `<html lang="en">
                      <head>
                        <meta charset="UTF-8" />
                        <title>Document</title>
                      </head>
                    <body>` +
                    data +
                    `
                    </body>
                  </html>`;
 HTMLtoDOCX(data, null, {
                    table: { row: { cantSplit: true } },
                    footer: true,
                    pageNumber: true,
                  })
                    .then((fileBuffer) => {
                      fs.writeFile("./document.docx", fileBuffer, (error) => {
                        if (error) {
                          console.log("Docx file creation failed");
                          return;
                        }
                        console.log("Docx file created successfully");
                      });
                    })
                    .catch((err) => {
                      alert(err);
               });
```
This is my rendition of the code.

### **My enviroment:**

macOS: 12.0 Beta
package version: 1.2.4
node version: v16.3.0

Thank you

**Comment by privateOmega** [comment]
Could you possibly post the html string you used? looks like either a bug or an edge case

**Comment by zees98** [comment]
Apologies for replying so late.

This is my html string. 
`<h2>Hello, World!</h2><p>This is some text over here.</p>`

**Comment by privateOmega** [comment]
@zees98 No worries, Its quite unlikely that the package failed with that html string because I am able to generate it without any issue on my laptop with react-example in the `examples/` in this repo.

Could you please let me know what's the end result after clone this repository, and run the example and try it out? I am super curious about this issue.

[html-to-docx.docx](https://github.com/privateOmega/html-to-docx/files/7212669/html-to-docx.2.docx)

**Comment by zees98** [comment]
Thank you for the reply. 
I will clone the example and let you know. 
Cheers

**Comment by zees98** [comment]
@privateOmega 
Hello again.
So I tried the example and the error I was facing is gone. I also took some assistance from one of your closed issues since my use case is with ReactJS as well.
But now I am receiving another error.
`Unhandled Rejection (TypeError): Cannot call a class as a function

My HTML string:
```
<!DOCTYPE html><html lang="en">
                      <head>
                        <meta charset="UTF-8" />
                        <title>Document</title>
                      </head>
                    <body><h2>Hello World!</h2>
                    </body>
                  </html>
```
The altered method: 
```
import HTMLtoDOCX from 'html-to-docx';
import { save } from 'file-save'

const html2DocConverter = async () => {
    var html = `<!DOCTYPE html><html lang="en">
                      <head>
                        <meta charset="UTF-8" />
                        <title>Document</title>
                      </head>
                    <body>` +
      text +
      `
                    </body>
                  </html>`;
    console.log(html);
    const fileBuffer = await HTMLtoDOCX(html, null, {
      table: { row: { cantSplit: true } },
      footer: true,
      pageNumber: true,
    });
    await save(fileBuffer, 'trial.docx');
  }
```

**Comment by privateOmega** [comment]
@zees98 That just didnt make any sense to me, since you havent really changed any part of the code wrt html-to-docx, but I did notice that you are using a package called file-save, if its the [one on npm](https://www.npmjs.com/package/file-save) , then you are using it wrong and that could be the origin of your error. If you still feel its an issue with html-to-docx, I would suggest for you to upload a sandbox repo for both of us to try out and replicate the issue.

**Comment by privateOmega** [comment]
Oh just noticed that the same issue was reported in #92 , hence closing the issue to track it there.

**Comment by privateOmega** [comment]
@zees98 I might possibly have figured out the issue, please follow the step in the other issue.
